### PR TITLE
Fixes #60 change import to include

### LINKED ISSUE #60: handler: regenerate grub2 conf not working on ansible 2.8
$ ansible --version
ansible 2.8.3

I think it needs to be `include_tasks: tasks/RedHat/generic/regenerate-grub2-conf.yml`; I'll pr it

### PR DESCRIPTION
**Pull request by Klaas-**
I also fixed the indentation for the other handler

### CODE REVIEW

**Review by berndfinger — COMMENTED** [review]
We want to use import_tasks as often as possible, for performance and other reasons, see https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#playbooks-reuse. I review and fix the wrong indentations with the next pull request.

**Comment by Klaas-** [comment]
It's not working with import_tasks, at least it did not when I opened that PR :) I am not sure if the ansible behaviour changed.

**Comment by berndfinger** [comment]
Thanks for this. Note that I am using import_tasks for many generic yml files in sap-preconfigure and sap-hana-preconfigure. However, there might be an issue in this case, due to the statement "Handlers using import* will not be triggered when notified by their name, as importing overwrites the handler’s named task with the imported task list." in https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#playbooks-reuse . Will check and clarify within the next days.

**Comment by berndfinger** [comment]
Many thanks again Klaas. Looks like your solution was the only one which worked!
Please see pull request #82 .

**Comment by berndfinger** [comment]
Solved in pull request #82 .

**Pull request closed without merging**
