### PR TITLE
Update disable-firewall.yml

### PR DESCRIPTION
**Pull request by tbludau**
firewalld not installed in minimal image

### CODE REVIEW

**Comment by makentenza** [comment]
@tbludau did you consider using [service_facts](https://docs.ansible.com/ansible/latest/modules/service_facts_module.html#service-facts-module) module instead to gather this info for 'firewalld.service'?

**Comment by tbludau** [comment]
@makentenza this could work, if the service_facts can identify if the service is installed. 
The problem was if i tried to disable the firewalld service there was a failure, because it wasn't installed on the system.
The return value from service_facts only shows unknowns a value. Or do this service_facts deliver all installed services from the system? in this case it could work.

**Comment by makentenza** [comment]
Yes, you will get a dictionary like this:
```
{
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python",
        "services": {
            "NetworkManager-dispatcher.service": {
                "name": "NetworkManager-dispatcher.service",
                "source": "systemd",
                "state": "unknown",
                "status": "enabled"
            },
            "NetworkManager-wait-online.service": {
                "name": "NetworkManager-wait-online.service",
                "source": "systemd",
                "state": "stopped",
                "status": "enabled"
            },
            //...
            //...
            "firewalld.service": {
                "name": "firewalld.service",
                "source": "systemd",
                "state": "unknown",
                "status": "disabled"
            }
        }
    }
}
```
So you can evaluate if the service is part of the system or not

**Comment by tbludau** [comment]
Thanks, i will check if this is working and will give you a feedback.

**Comment by makentenza** [comment]
Great, thanks @tbludau!

**Comment by tbludau** [comment]
Tested it and it works as expected. When firewalld is installed, it will change the state, if not, it will skip.

**Review by makentenza — APPROVED** [review]
LGTM

**Comment by berndfinger** [comment]
fine for me. I might however change this to something similiar to https://github.com/berndfinger/sap-preconfigure/blob/master/tasks/RedHat/generic/configure-firewall.yml later.

**Pull request merged**
